@startuml

class Item {
'attributes
    - id : String
    - name : String
    - price : String

'methods
    +Task(String id, String name, String price)

    +setId(String id)
    +setName(String name)
    +setPrice(String price)

    +getId() : String
    +getName() : String
    +getPrice() : String
}

class ApplicationController{
'attributes
    - tableView : TableView<Task>
    - idColumn : TableColumn<Task, String>
    - nameColumn : TableColumn<Task, String>
    - priceColumn : TableColumn<Task, String>

    - idField : TextField
    - nameField : TextField
    - priceField : TextField
    - searchIdField : TextField
    - searchNameField : TextField
    - statusMessageTxt : Label
    - vBoxMain : VBox

'methods
    -newItem()

    -openList()
    -downloadList()

    -deleteItem()
    -clearAll()

    -changeId()
    -changeName()
    -changePrice()

    -search()

    -darkMode()

    +initialize()
}

class InventoryManagementApplication{
'methods
    +main(String[] args)
    +start(Stage stage)
}

class Functionality{
'methods
    +openTXTFile(File selectedFile): ObservableList<Item>
    +downloadTXTFile(File selectedFile, ObservableList<Item> list)
    +openJSONFile(File selectedFile): ObservableList<Item>
    +downloadJSONFile(File selectedFile, ObservableList<Item> list)
    +openHTMLFile(File selectedFile): ObservableList<Item>
    +downloadHTMLFile(File selectedFile, ObservableList<Item> list)

    +isIdUnique(String id): boolean
}

@enduml